// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: authentication/login_validation.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginValidationRequest) Reset() {
	*x = LoginValidationRequest{}
	mi := &file_authentication_login_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginValidationRequest) ProtoMessage() {}

func (x *LoginValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_login_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginValidationRequest.ProtoReflect.Descriptor instead.
func (*LoginValidationRequest) Descriptor() ([]byte, []int) {
	return file_authentication_login_validation_proto_rawDescGZIP(), []int{0}
}

func (x *LoginValidationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginValidationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginValidationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginValidationRequest) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type LoginValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValidated   bool                   `protobuf:"varint,1,opt,name=isValidated,proto3" json:"isValidated,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	LastLogin     string                 `protobuf:"bytes,3,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginValidationResponse) Reset() {
	*x = LoginValidationResponse{}
	mi := &file_authentication_login_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginValidationResponse) ProtoMessage() {}

func (x *LoginValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_login_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginValidationResponse.ProtoReflect.Descriptor instead.
func (*LoginValidationResponse) Descriptor() ([]byte, []int) {
	return file_authentication_login_validation_proto_rawDescGZIP(), []int{1}
}

func (x *LoginValidationResponse) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

func (x *LoginValidationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginValidationResponse) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *LoginValidationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_authentication_login_validation_proto protoreflect.FileDescriptor

var file_authentication_login_validation_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x22, 0x89, 0x01, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x08, 0x5a, 0x06, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_authentication_login_validation_proto_rawDescOnce sync.Once
	file_authentication_login_validation_proto_rawDescData = file_authentication_login_validation_proto_rawDesc
)

func file_authentication_login_validation_proto_rawDescGZIP() []byte {
	file_authentication_login_validation_proto_rawDescOnce.Do(func() {
		file_authentication_login_validation_proto_rawDescData = protoimpl.X.CompressGZIP(file_authentication_login_validation_proto_rawDescData)
	})
	return file_authentication_login_validation_proto_rawDescData
}

var file_authentication_login_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authentication_login_validation_proto_goTypes = []any{
	(*LoginValidationRequest)(nil),  // 0: LoginValidationRequest
	(*LoginValidationResponse)(nil), // 1: LoginValidationResponse
}
var file_authentication_login_validation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_login_validation_proto_init() }
func file_authentication_login_validation_proto_init() {
	if File_authentication_login_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authentication_login_validation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_login_validation_proto_goTypes,
		DependencyIndexes: file_authentication_login_validation_proto_depIdxs,
		MessageInfos:      file_authentication_login_validation_proto_msgTypes,
	}.Build()
	File_authentication_login_validation_proto = out.File
	file_authentication_login_validation_proto_rawDesc = nil
	file_authentication_login_validation_proto_goTypes = nil
	file_authentication_login_validation_proto_depIdxs = nil
}
