// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: users_administration/users_administration.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsersAdministrationService_UsersList_FullMethodName = "/model.UsersAdministrationService/UsersList"
)

// UsersAdministrationServiceClient is the client API for UsersAdministrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersAdministrationServiceClient interface {
	UsersList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsersListResponse, error)
}

type usersAdministrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersAdministrationServiceClient(cc grpc.ClientConnInterface) UsersAdministrationServiceClient {
	return &usersAdministrationServiceClient{cc}
}

func (c *usersAdministrationServiceClient) UsersList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsersListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersListResponse)
	err := c.cc.Invoke(ctx, UsersAdministrationService_UsersList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersAdministrationServiceServer is the server API for UsersAdministrationService service.
// All implementations should embed UnimplementedUsersAdministrationServiceServer
// for forward compatibility.
type UsersAdministrationServiceServer interface {
	UsersList(context.Context, *emptypb.Empty) (*UsersListResponse, error)
}

// UnimplementedUsersAdministrationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersAdministrationServiceServer struct{}

func (UnimplementedUsersAdministrationServiceServer) UsersList(context.Context, *emptypb.Empty) (*UsersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersList not implemented")
}
func (UnimplementedUsersAdministrationServiceServer) testEmbeddedByValue() {}

// UnsafeUsersAdministrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersAdministrationServiceServer will
// result in compilation errors.
type UnsafeUsersAdministrationServiceServer interface {
	mustEmbedUnimplementedUsersAdministrationServiceServer()
}

func RegisterUsersAdministrationServiceServer(s grpc.ServiceRegistrar, srv UsersAdministrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedUsersAdministrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsersAdministrationService_ServiceDesc, srv)
}

func _UsersAdministrationService_UsersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersAdministrationServiceServer).UsersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersAdministrationService_UsersList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersAdministrationServiceServer).UsersList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersAdministrationService_ServiceDesc is the grpc.ServiceDesc for UsersAdministrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersAdministrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.UsersAdministrationService",
	HandlerType: (*UsersAdministrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsersList",
			Handler:    _UsersAdministrationService_UsersList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users_administration/users_administration.proto",
}
